### ISSUE TITLE
The app is constantly crashing in Homey 2.0.1

### ISSUE THREAD

**Issue by rafi1975** [abaretta/nu.baretta.tplink#9]
The app is constantly crashing in Homey 2.0.1. Not usable at all.

**Comment by GithubBram** [comment]
Unfortunately my router is not able to use static IPs. IPs are changing all the time for my TP Link devices and also with v0.1.1 it does not seem to work: Homey does not remember the devices.

**Comment by nieuwe** [comment]
Homey v2.0
Several times the app stopped working
Before v2.0 everything ran well

**Comment by PutzJimmy** [comment]
I have the same problem and I have my devices on static IP's and tried the following with no result.
Restart the app - might work for a few min or so then crash.
Restart homey - might work for a tad bit longer but then crash.
Reinstall the app - Works the longest but then crash.

**Comment by abaretta** [comment]
I have updated the app and submitted it to the app store yesterday. It can be installed through the 'CLI method' (search the forum for 'CLI HOWTO' or something similar) right now, and of course once approved by Athom it will be available in the app store as well.

**Comment by rafi1975** [comment]
How do you install it via cli on Homey v2.0?
I tried and the command is not available any more.

**Comment by abaretta** [comment]
https://community.athom.com/t/how-to-cli-install-method/198

**Comment by abaretta** [comment]
Since the upgrade I am not receiving crashreports anymore, seems to work :)

**Comment by nieuwe** [comment]
Looks working fine now
No more crashes

Thanks a lot

**Comment by rafi1975** [comment]
Still crashes with v.2 but you don't have it installed. For me it means probably going away to a different controller. I have only a few devices running with the new version of Homey. 3/4th of the rest not working. This has been reported to Homey but for the last two weeks no reply.

C:\Users\rafal\Downloads\Homey\nu.baretta.tplink-master>athom app run
✓ Pre-processing app…
✓ Validating app…
✓ Homey App validated successfully against level debug
✓ Packing Homey App…
— App size: 1.68 MB
✓ Installing Homey App on Homey (https://192-168-1-142.homey.homeylocal.com)…
✓ Homey App nu.baretta.tplink successfully installed
✓ Running nu.baretta.tplink, press CTRL+C to quit
— Profile your app’s performance at https://go.athom.com/app-profiling?homey=5881f9f0e9dd2f810d32d2de&app=nu.baretta.tplink
─────────────── Logging stdout & stderr ───────────────
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [0] device init
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [0] id: 192.168.1.144
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [0] name: En suite Radiator
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [0] class: socket
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [0] settings IP address: 192.168.1.144
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [0] dynamicIp is defined: false
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [0] settings totalOffset: undefined
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [1] device init
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [1] id: 192.168.1.143
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [1] name: Main Bathroom Radiator
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [1] class: socket
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [1] settings IP address: 192.168.1.143
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [1] dynamicIp is defined: false
2019-01-28 13:38:11 [log] [ManagerDrivers] [hs110] [1] settings totalOffset: undefined
2019-01-28 13:38:21 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:38:21 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:38:24 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 1 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:24 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:38:24 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 2 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:24 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:38:31 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:38:31 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:38:34 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 3 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:34 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:38:34 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 4 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:34 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:38:41 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:38:41 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:38:44 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 5 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:44 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:38:44 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 6 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:44 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:38:51 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:38:51 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:38:54 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 7 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:54 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:38:54 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 8 Discover count: 0 DynamicIP option: false
2019-01-28 13:38:54 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:01 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:39:01 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:39:04 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 9 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:04 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:04 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 10 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:04 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:11 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:39:11 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:39:14 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 11 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:14 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:14 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 12 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:14 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:21 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:39:21 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:24 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 13 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:24 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:39:24 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 14 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:24 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:31 [log] [ManagerDrivers] [hs110] [0] getStatus device: 192.168.1.144
2019-01-28 13:39:31 [log] [ManagerDrivers] [hs110] [1] getStatus device: 192.168.1.143
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.143:9999
2019-01-28 13:39:34 [log] [ManagerDrivers] [hs110] [1] Device unreachable. Unreachable count: 15 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:34 [log] [ManagerDrivers] [hs110] [1] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.143:9999
[undefined] device.send() Error: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:34 [log] [ManagerDrivers] [hs110] [0] Device unreachable. Unreachable count: 16 Discover count: 0 DynamicIP option: false
2019-01-28 13:39:34 [log] [ManagerDrivers] [hs110] [0] Caught error in getStatus / getSysInfo function: connect EHOSTUNREACH 192.168.1.144:9999
2019-01-28 13:39:38 [log] [ManagerDrivers] [hs110] [1] Capability called: onoff value: true
/drivers/hs110/device.js:140
this.LedOn(device);
^
TypeError: this.LedOn is not a function
at TPlinkPlugDevice.onCapabilityLedOnoff (/drivers/hs110/device.js:140:18)
at TPlinkPlugDevice.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:1934)
at emitTwo (events.js:126:13)
at TPlinkPlugDevice.emit (events.js:214:7)
at TPlinkPlugDriver.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:1511)
at emitTwo (events.js:126:13)
at TPlinkPlugDriver.emit (events.js:214:7)
at Homey.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:1506)
at SDK._onReady (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:1045)
at ManagerDrivers._onEventDriverMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:1424)
— INFO: nu.baretta.tplink has been killed —

**Comment by rafi1975** [comment]
It's been nine months since I reported that issue and there's been no reply to it. Has this been abandoned?
The app keeps crashing everyday even with the latest Homey version.

**Comment by PutzJimmy** [comment]
I haven't had a problem with it since the update back in jan.

**Comment by abaretta** [comment]
I rarely receive crashreports for the app, so it is definitely not a general issue. 

I doubt it’s crashing every day on your Homey or I would receive crashreports every day...

I do think some crashes are caused by the memory leak in the Homey core that affects some users, including myself. If I don’t reboot every few days Homey will become unresponsive. 

Anyway, as it is not a general problem you need to come with more details.
